=== HelenCSWS/CS-Online/php2go/docs/dtd/php2go_forms.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- DTD que especifica a forma de construção dos arquivos XML de formulários do PHP2Go -->
<!-- $Header: /www/cvsroot/php2go/docs/dtd/php2go_forms.dtd,v 1.22 2005/09/01 13:55:42 mpont Exp $ -->
<!-- $Revision: 1.22 $ -->
<!-- $Date: 2005/09/01 13:55:42 $ -->
<!ELEMENT form (section+, condsection*)>
<!ATTLIST form
	validatefunc CDATA #IMPLIED
>
<!ELEMENT section (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, datagrid*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST section
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	condition (T | F) #IMPLIED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT condsection (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST condsection
	id CDATA #REQUIRED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT captchafield (listener*, rule*)>
<!ATTLIST captchafield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	noiselevel CDATA #IMPLIED
	fontsize CDATA #IMPLIED
	fontshadow CDATA #IMPLIED	
	fontangle CDATA #IMPLIED
	imagepath CDATA #IMPLIED
	imagetype CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED	
>
<!ELEMENT checkfield (listener*, rule*, search?)>
<!ATTLIST checkfield
	name CDATA #REQUIRED
	label CDATA #IMPLIED
	default CDATA #IMPLIED
	caption CDATA #REQUIRED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT checkgroup (option+, listener*, rule*, search?)>
<!ATTLIST checkgroup
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT combofield (option+, listener*, rule*, search?)>
<!ATTLIST combofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple CDATA #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT dbradiofield (datasource, listener*, rule*, search?)>
<!ATTLIST dbradiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT editfield (listener*, rule*, search?)>
<!ATTLIST editfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	mask (INTEGER | FLOAT | LOGIN | DATE | TIME | CPFCNPJ | CURRENCY | URL | EMAIL | ZIPnn) #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	calculator (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	capitalize (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
>
<!ELEMENT editorfield EMPTY>
<!ATTLIST editorfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT editsearchfield (datafilter+, datasource, lookupfield, listener*)>
<!ATTLIST editsearchfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	btnvalue CDATA #IMPLIED
	btnimg CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
	required (T | F) #IMPLIED	
	disabled (T | F) #IMPLIED	
	debug (T | F) #IMPLIED
>
<!ELEMENT editselectionfield (editfield, lookupfield)>
<!ATTLIST editselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	tablewidth CDATA #IMPLIED
>
<!ELEMENT filefield (listener*, rule*)>
<!ATTLIST filefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	maxfilesize CDATA #IMPLIED
	allowedtypes CDATA #IMPLIED
	savefunction CDATA #IMPLIED
	savepath CDATA #IMPLIED
	savename CDATA #IMPLIED
	savemode CDATA #IMPLIED
	overwrite (T | F) #IMPLIED
	uploadonvalidate (T | F) #IMPLIED
>
<!ELEMENT datagrid (datasource, fieldset)>
<!ATTLIST datagrid
	name CDATA #REQUIRED
	label CDATA #REQUIRED	
	headerstyle CDATA #IMPLIED
	cellstyle CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	cellsizes CDATA #IMPLIED
	help CDATA #IMPLIED	
	disabled (T | F) #IMPLIED	
>
<!ELEMENT hiddenfield (search?)>
<!ATTLIST hiddenfield
	name CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
>
<!ELEMENT lookupchoicefield (datasource, listener*, rule*, search?)>
<!ATTLIST lookupchoicefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT lookupfield (datasource?, listener*, rule*, search?)>
<!ATTLIST lookupfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	size CDATA #IMPLIED
>
<!ELEMENT lookupselectionfield (lookupfield+)>
<!ATTLIST lookupselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	addallimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
>
<!ELEMENT memofield (listener*, rule*, search?)>
<!ATTLIST memofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	charcount (T | F) #IMPLIED
>
<!ELEMENT passwdfield (listener*, rule*, search?)>
<!ATTLIST passwdfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT radiofield (option+, listener*, rule*, search?)>
<!ATTLIST radiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT rangefield (edifield*, search?)>
<!ATTLIST rangefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	surroundtext CDATA #IMPLIED	
	startname CDATA #IMPLIED	
	endname CDATA #IMPLIED
	ruleequal (T | F) #IMPLIED
	rulemessage CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
>
<!ELEMENT textfield EMPTY>
<!ATTLIST textfield
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	default CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
>
<!ELEMENT buttons (button+)>
<!ELEMENT button (listener*)>
<!ATTLIST button
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	type (SUBMIT | RESET | BUTTON | CLEAR) #REQUIRED
	img CDATA #IMPLIED
	swpimg CDATA #IMPLIED
	alt CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT listener EMPTY>
<!ATTLIST listener
	event (onFocus | onBlur | onChange | onKeyUp | onKeyDown | onMouseUp | onMouseDown | onClick | onDblClick) #REQUIRED
	type (JS | JSRS) #REQUIRED
	action CDATA #IMPLIED
	remote CDATA #IMPLIED
	callback CDATA #IMPLIED
	params CDATA #IMPLIED
	file CDATA #IMPLIED
	debug (T | F) #IMPLIED
	autodispatchif CDATA #IMPLIED
>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
	type (REGEX | EQ | NEQ | GT | LT | GOET | LOET | REQIF | REQIFEQ | REQIFNEQ | REQIFGT | REQIFLT | REQIFGOET | REQIFLOET) #REQUIRED
	field CDATA #IMPLIED
	value CDATA #IMPLIED
	message CDATA #IMPLIED
	comparetype (STRING | INTEGER | FLOAT | DATE) #IMPLIED
>
<!ELEMENT search EMPTY>
<!ATTLIST search
	alias CDATA #IMPLIED
	datatype (STRING | INTEGER | FLOAT | DATE | DATETIME) #IMPLIED
	operator (EQ | NEQ | GT | LT | GOET | LOET | STARTING | ENDING | CONTAINING | IN | NOTIN | BETWEEN) #IMPLIED
	sqlfunc CDATA #IMPLIED
	fieldfunc CDATA #IMPLIED
	valuefunc CDATA #IMPLIED
>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	id CDATA #REQUIRED
	label CDATA #REQUIRED
	expression CDATA #REQUIRED
	mask CDATA #IMPLIED
>
<!ELEMENT datasource (keyfield, displayfield?, lookuptable, clause?, groupby?, orderby?, limit?, groupfield?, groupdisplay?, procedure?)>
<!ATTLIST datasource
	connection CDATA #IMPLIED
>
<!ELEMENT keyfield (#PCDATA)>
<!ELEMENT displayfield (#PCDATA)>
<!ELEMENT lookuptable (#PCDATA)>
<!ELEMENT clause (#PCDATA)>
<!ELEMENT groupby (#PCDATA)>
<!ELEMENT orderby (#PCDATA)>
<!ELEMENT limit (#PCDATA)>
<!ELEMENT groupfield (#PCDATA)>
<!ELEMENT groupdisplay (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ATTLIST procedure
	cursorname CDATA #IMPLIED
>
<!ELEMENT option (listener*)>
<!ATTLIST option
	value CDATA #REQUIRED
	caption CDATA #IMPLIED
	alt CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT fieldset (editfield*, passwdfield*, memofield*, checkfield*, lookupfield*, radiofield*, dbradiofield*, checkgroup*, combofield*)>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/comm_levels_type1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Form60 : template used in AddUser.php -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form  >


	<section name="My Section" id="commLevels" required_flag="T" required_color="#FF0000" required_char="*">
        <!-- row1 estate name, number, delivery date-->

		<hiddenfield name="pageid" value="39"/>
		<hiddenfield name = "levels"  value = "0" />	
		<hiddenfield name = "bcldb_levels"  value = "0" />
		<hiddenfield name = "bonus"  value = "0" />
		<hiddenfield name = "is_save"  value = "0" />
		<hiddenfield name = "is_bcldb"  value = "0" />		
		<hiddenfield name = "is_float"  value = "0" />
		<hiddenfield name = "level"  value = "0" />
		<hiddenfield name = "province_id"  value = "0" />
		
		<hiddenfield name = "sales_commission_level_id"  value = "0" />
	
		<hiddenfield name = "lkup_commission_sales_sum_type_id"  value = "0" />
	
		<hiddenfield name = "user_id"  value = "0" />
		
		<hiddenfield name = "lkup_sales_commission_type_id"  value = "1" />
		

      <!--section 1  REGUALR STORE -->
  
		<editfield name="min_intl_cases"   value="100" label="International wine cases"    size="7" length="25" required="T" tabindex="1"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,0)"/>
		</editfield>
		
		<editfield name="min_canadian_cases"  value="80" label="Canadian wine cases"    size="7" length="25" required="T" tabindex="2"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,1)"/>
		</editfield>
		
		<editfield name="bonus_d" label="Bonus for minimum target" tabindex="3" size="7" length="25" >
			<listener type="JS" event="onblur" action="setPrice(this,4)"/>
			<listener type="JS" event="onKeyPress" action="return chkFLOAT4B(this,event);"/>
		</editfield>
		
		<editfield name="min_cases1"   label="Cases"    size="10" length="25"  tabindex="4"  autotrim="T" mask="float"/>	
		
		<editfield name="max_cases1"   label="Cases"    size="10" length="25"  tabindex="5"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,2)"/>
		</editfield>
		
		<editfield name="comm1"     label="Commission %"    size="13" length="25"  tabindex="6" autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="checkOverComm(this,1)"/>
		</editfield>
		
		<editfield name="min_cases2"   label="Cases"    size="10" length="25"  tabindex="7"  autotrim="T" mask="float"/>
		<editfield name="max_cases2"   label="Cases"    size="10" length="25"  tabindex="8"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,3)"/>
		</editfield>
		
		<editfield name="comm2"     label="Commission %"    size="13" length="25" tabindex="9" autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="checkOverComm(this,2)"/>
		</editfield>
		
		<editfield name="min_cases3"   label="Cases"   size="10" length="25"  tabindex="10"  autotrim="T" mask="float"/>
		
		<editfield name="max_cases3"   label="Cases"     size="10" length="25"  tabindex="11"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,4)"/>
		</editfield>
		
		<editfield name="comm3"     label="Commission %"    size="13" length="25"  tabindex="12" autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="checkOverComm(this,3)"/>
		</editfield>
		
		
		<editfield name="min_cases4"   label="Cases"    size="10" length="25"  tabindex="13"  autotrim="T" mask="float"/>
		
		<editfield name="max_cases4"   label="Cases"    size="10" length="25"  tabindex="14"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,5)"/>
		</editfield>
		
		<editfield name="comm4"     label="Commission %"     size="13" length="25"  tabindex="15" autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="checkOverComm(this,4)"/>
		</editfield>
		
		<editfield name="min_cases5"   label="Cases"    size="10" length="25"  tabindex="16"  autotrim="T" mask="float"/>
		
		<editfield name="max_cases5"   label="Cases"     size="10" length="25"  tabindex="17"  autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="setCases(this,6)"/>
		</editfield>
		
		<editfield name="comm5"     label="Commission %"    size="13" length="25"  tabindex="18" autotrim="T" mask="float">
			<listener type="JS" event="onblur" action="checkOverComm(this,5)"/>
		</editfield>


            <!--buttons note -->
		<buttons>
			<button name="btnBack" type="BUTTON"  value="Back" tabindex="29">
		        <listener type="JS" event="onClick" action="openPage(0)"/>
		    </button>
		    
			<button name="btnAddNext" type="BUTTON"  value="Next" tabindex="29" />
		    
			<button name="btnAdd" type="BUTTON"  value="OK" tabindex="29"/>
			
     		<button name="btnCancel" id="btnCancel" type="BUTTON" value="Cancel" tabindex="30"/>
		</buttons>


	</section>

</form>



	<!-- Form60 : template used in addestate.php -->

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectPeriod.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="selectperiod" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="pageid" value="42"/>
                <hiddenfield name="is_recreate" value="0"/>
                <hiddenfield name="contact_key" value="1"/>


      
       <lookupfield name="fiscal_year"  tabindex="2" default="2007" nofirst="T" multiple="F" size="1" width="200" >
            <datasource>
                <keyfield>fiscal_year</keyfield>
                        <displayfield>display_name</displayfield>
                        <orderby>fiscal_year</orderby>
                <lookuptable>fiscal_years</lookuptable>
            </datasource>
            
            <listener type="JS" event="onChange" action="getPeriodsByFiscalYear(this.value)"/>

        </lookupfield>
      
      


        <combofield name="period" nofirst="T" width="100"  >
 			<listener type="JS" event="onChange" action="changePeriod(this.value)"/>
        </combofield>

    

	

      <textfield name="period_desc" tabindex="1" value="test" readonly="F" />
	
	

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/addnewuser.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="Add new user" id="addnewuser" required_flag="T" required_color="#FF0000" required_char="*">
         <hiddenfield name="pageid" value="12"/>
         <hiddenfield name="lkup_user_type_id" value="0"/>

	
        <hiddenfield name="user_id"/>
        <editfield name="first_name" label="First name"  tabindex="1" size="28" length="25" required="T"/>
		<editfield name="last_name" label="Last name" tabindex="2" size="28" length="25" required="T"/>
		<editfield name="phone_cell" label="Cell number" tabindex="3" size="28" length="25" >
        		<!--listener type="JS" event="onfocusout" action="setformat(this.value)"/-->
        </editfield>
		<editfield name="email1" label="Email address" mask="EMAIL" tabindex="4" size="28" length="100"/>
		<editfield name="username" label="Username"  tabindex="5" size="28" length="25" minlength="5" required="T"/>
		
		<passwdfield name="userpass" label="Password" tabindex="6" size="28" length="50" minlength="5" required="T"/>

                <passwdfield name="repeatuserpass" label="Retype password" tabindex="7" size="28" length="50" minlength="5" required="T">
                        <rule type="EQ" field="userpass" message="The passwords do not match, please try again."/>
                </passwdfield>

		<lookupfield name="user_level_id" label="User level"  tabindex="8" default="4" nofirst="T" multiple="F" size="1" width="105" required="T" >
			<datasource>
				<keyfield>user_level_id</keyfield>
                                <displayfield>caption</displayfield>
                                <orderby>user_level_id</orderby>
				<lookuptable>user_levels</lookuptable>
			</datasource>
                        <listener type="JS" event="onChange" action="changesectlevel()"/>
		</lookupfield>
		
		<lookupfield name="estate_id" label="Estate"  tabindex="8" default="1" nofirst="T" multiple="F" size="1" width="182" required="T" >
			<datasource>
				<keyfield>estate_id</keyfield>
                                <displayfield> if(estate_id=96, 'Enotecca winery' ,estate_name) </displayfield>
                                <orderby>estate_name</orderby>
				<lookuptable>estates</lookuptable>
				<clause>estate_id!=97 and deleted=0 </clause>
			</datasource>
                        <listener type="JS" event="onChange" action="changesectlevel()"/>
		</lookupfield>
		
		<lookupfield name="province_id" label="Province"  tabindex="9" default="1" nofirst="T" multiple="F" size="1" width="70" required="T" >
			<datasource>
				<keyfield>province_id</keyfield>
                  <displayfield>short_name</displayfield>
                  <orderby>province_id</orderby>
				<lookuptable>lkup_provinces</lookuptable>
			</datasource>
                     
		</lookupfield>


		<buttons>
			<button name="btnAdd" type="BUTTON"  value="OK  " tabindex="10"/>
            <!--button name="btnAddAnother" type="BUTTON" value="Add another user" tabindex="9"/-->
			<button name="btnCancel" type="BUTTON" value="Cancel" tabindex="11"/>
		</buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/allocateNewWine.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="allocatewine" id="allocatewine" required_flag="T" required_color="#FF0000" required_char="*">
	        <hiddenfield name="wine_numbers"/>
	        <hiddenfield name="wine_ids"/>
	        <hiddenfield name="all_wine_ids"/>
	        <hiddenfield name="pageid"/>

	        <hiddenfield name="estate_id"/>


    		<buttons>
    			<button name="btnAllocate"   type="BUTTON"  value=" Allocate now " >
                              <listener type="JS" event="onclick" action="allocateWine()"/>
    			</button>
    			<button name="btnSave"       type="BUTTON"  value="OK  " >
                               <listener type="JS" event="onclick" action="saveAllocate()"/>
    			</button>
     			<button name="btnCancel"     type="BUTTON" value="Cancel" />
    		</buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/f60overduereports.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="f60overduereports" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="estate" value="0"/>
                <hiddenfield name="isWine" value="0"/>
                <hiddenfield name="isQtr" value="0"/>
                <hiddenfield name="isStart" value="0"/>
                
            		
               
              

        <lookupfield name="estate_id"  label="Estate" tabindex="1" nofirst="T" multiple="F" size="1" width="195" >
			<datasource>
				<keyfield>estate_id</keyfield>
                                <displayfield>estate_name</displayfield>
                                <clause>deleted=0 and billing_address_country like '%Canada%' and deleted=0</clause>
                                <orderby>estate_name</orderby>
				<lookuptable>estates</lookuptable>
			</datasource>
		</lookupfield>
		
		<lookupfield name="lkup_store_type_id"  label="Store type" tabindex="1" nofirst="F" multiple="F" size="1" width="130">
			<datasource>
				<keyfield>lkup_store_type_id</keyfield>
                                <displayfield>license_name</displayfield>
                                <clause>lkup_store_type_id !=8 and lkup_store_type_id!=4 and lkup_store_type_id!=6</clause>
                                <orderby>caption</orderby>
				<lookuptable>lkup_store_types</lookuptable>
			</datasource>
		</lookupfield>
		
		<lookupfield name="user_id"  label="Assigned to" tabindex="1" nofirst="F" multiple="F" size="1" width="130">
			<datasource>
				<keyfield>user_id</keyfield>
                    <displayfield>concat(first_name,' ', last_name)</displayfield>
                    <clause>deleted=0 and user_level_id!=5 and user_level_id!=6 and user_id!=26 and (user_id =7 or user_id=6 or user_id =51 or user_id = 22 or user_id =43 )and (province_id=1) </clause>
                                <orderby>first_name</orderby>
				<lookuptable>users</lookuptable>
			</datasource >
		</lookupfield>
		
	<combofield name="overdue_type" label="Overdue days" nofirst="T" multiple="F" size="1" default="3" width="195" disabled="F" tabindex="4">
	        <option value="0" caption=" All "/>
	        <option value="1" caption=" 31 to 60 days"/>
   	        <option value="2" caption=" 60 to 90 days"/>
   	        <option value="3" caption=" Over 90 days"/>

      </combofield>
	

	</section>

</form>
<!-- -->

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectGetCaWines.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="searchf60" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="search_id" value="0"/>
                <hiddenfield name="contact_key" value="1"/>


       
      <textfield name="fiscal_year" tabindex="1" value="Apr 01,2006 - Mar 31,2007" size="100"/>
     <textfield name="period_desc" tabindex="1" value="Preiod 9: Nov 26,2006 - Dec 30,2006" size="100"/>
     <textfield name="user" tabindex="1" value="Tyler Mackenzie" size="100"/>
     <editField name="total_cases" tabindex="1" value="230" size="100"/>
     

		<buttons>
    		<button name="btnView" type="BUTTON" value="View reports" tabindex="2">
                 <listener type="JS" event="onClick" action="tempNextPage(1)"/>
    		</button>
			<button name="btnCancel" type="BUTTON" value="Cancel" tabindex="3"/>
		</buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectUpload.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>
   
	<section name="" id="selectEstate" required_flag="T" required_color="#FF0000" required_char="*">
        <hiddenfield name="pageid"/>
        <hiddenfield name="stestate_id"/>
        
        <hiddenfield name="search_id"/>
         <hiddenfield name="search_key"/>

		


		<!--lookupfield name="province"  label="Country" tabindex="1" default="1" nofirst="T" multiple="F"  width="180"  >
			<datasource>
				<keyfield>distinct billing_address_country</keyfield>
                <displayfield>billing_address_country</displayfield>
                <orderby>billing_address_country</orderby>
                <clause>deleted=0 </clause>
				<lookuptable>estates</lookuptable>
			</datasource>
			
			<listener type="JS" event="onChange" action="getEstatsByCountry('estate_id', this.value)"/>

		</lookupfield-->
		
		<combofield name="estate_id"  label="Estate" tabindex="1" default="1" nofirst="T" multiple="F" size="15" width="380"  >
		<>
		<listener type="JS" event="ondblclick" action="openPage()"/>
		</combofield>

		
		<combofield name="estate_id"  label="Estate" tabindex="1" default="1" nofirst="T" multiple="F" size="15" width="380"  >
		<listener type="JS" event="ondblclick" action="openPage()"/>
		</combofield>

 		<buttons>

            <button name="btnNext" type="BUTTON"  value="Next  " tabindex="2">
     		      <listener type="JS" event="onClick" action="openPage()"/>
    		</button>
    		
			<button name="btnCancel" type="BUTTON" value="Cancel" tabindex="3"/>
			
		</buttons>
     
	</section>	

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectSSDSMonth.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="selectperiod" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="pageid" value="42"/>
                <hiddenfield name="is_recreate" value="0"/>
                <hiddenfield name="contact_key" value="1"/>


      
       <lookupfield name="sale_year"  lable="Year" tabindex="2"  nofirst="T" multiple="F" size="1" width="100" >
            <datasource>
                <keyfield>distinct(sale_year)</keyfield>
                        <displayfield>sale_year</displayfield>
                        <orderby>sale_year desc limit 3</orderby>
                        <clause>province_id=~current_province_id~</clause>
                <lookuptable>user_sales_summary</lookuptable>
            </datasource>
            
            <listener type="JS" event="onChange" action="getMonthBySaleYear(this.value)"/>

        </lookupfield>
      
      


        <combofield lable="Month" name="sale_month" nofirst="T" width="100"  >
 			<!--listener type="JS" event="onChange" action="changePeriod(this.value)"/-->
        </combofield>
	</section>

</form>
