=== HelenCSWS/CS-Online/php2go/docs/dtd/php2go_forms.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- DTD que especifica a forma de construção dos arquivos XML de formulários do PHP2Go -->
<!-- $Header: /www/cvsroot/php2go/docs/dtd/php2go_forms.dtd,v 1.22 2005/09/01 13:55:42 mpont Exp $ -->
<!-- $Revision: 1.22 $ -->
<!-- $Date: 2005/09/01 13:55:42 $ -->
<!ELEMENT form (section+, condsection*)>
<!ATTLIST form
	validatefunc CDATA #IMPLIED
>
<!ELEMENT section (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, datagrid*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST section
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	condition (T | F) #IMPLIED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT condsection (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST condsection
	id CDATA #REQUIRED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT captchafield (listener*, rule*)>
<!ATTLIST captchafield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	noiselevel CDATA #IMPLIED
	fontsize CDATA #IMPLIED
	fontshadow CDATA #IMPLIED	
	fontangle CDATA #IMPLIED
	imagepath CDATA #IMPLIED
	imagetype CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED	
>
<!ELEMENT checkfield (listener*, rule*, search?)>
<!ATTLIST checkfield
	name CDATA #REQUIRED
	label CDATA #IMPLIED
	default CDATA #IMPLIED
	caption CDATA #REQUIRED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT checkgroup (option+, listener*, rule*, search?)>
<!ATTLIST checkgroup
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT combofield (option+, listener*, rule*, search?)>
<!ATTLIST combofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple CDATA #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT dbradiofield (datasource, listener*, rule*, search?)>
<!ATTLIST dbradiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT editfield (listener*, rule*, search?)>
<!ATTLIST editfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	mask (INTEGER | FLOAT | LOGIN | DATE | TIME | CPFCNPJ | CURRENCY | URL | EMAIL | ZIPnn) #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	calculator (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	capitalize (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
>
<!ELEMENT editorfield EMPTY>
<!ATTLIST editorfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT editsearchfield (datafilter+, datasource, lookupfield, listener*)>
<!ATTLIST editsearchfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	btnvalue CDATA #IMPLIED
	btnimg CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
	required (T | F) #IMPLIED	
	disabled (T | F) #IMPLIED	
	debug (T | F) #IMPLIED
>
<!ELEMENT editselectionfield (editfield, lookupfield)>
<!ATTLIST editselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	tablewidth CDATA #IMPLIED
>
<!ELEMENT filefield (listener*, rule*)>
<!ATTLIST filefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	maxfilesize CDATA #IMPLIED
	allowedtypes CDATA #IMPLIED
	savefunction CDATA #IMPLIED
	savepath CDATA #IMPLIED
	savename CDATA #IMPLIED
	savemode CDATA #IMPLIED
	overwrite (T | F) #IMPLIED
	uploadonvalidate (T | F) #IMPLIED
>
<!ELEMENT datagrid (datasource, fieldset)>
<!ATTLIST datagrid
	name CDATA #REQUIRED
	label CDATA #REQUIRED	
	headerstyle CDATA #IMPLIED
	cellstyle CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	cellsizes CDATA #IMPLIED
	help CDATA #IMPLIED	
	disabled (T | F) #IMPLIED	
>
<!ELEMENT hiddenfield (search?)>
<!ATTLIST hiddenfield
	name CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
>
<!ELEMENT lookupchoicefield (datasource, listener*, rule*, search?)>
<!ATTLIST lookupchoicefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT lookupfield (datasource?, listener*, rule*, search?)>
<!ATTLIST lookupfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	size CDATA #IMPLIED
>
<!ELEMENT lookupselectionfield (lookupfield+)>
<!ATTLIST lookupselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	addallimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
>
<!ELEMENT memofield (listener*, rule*, search?)>
<!ATTLIST memofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	charcount (T | F) #IMPLIED
>
<!ELEMENT passwdfield (listener*, rule*, search?)>
<!ATTLIST passwdfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT radiofield (option+, listener*, rule*, search?)>
<!ATTLIST radiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT rangefield (edifield*, search?)>
<!ATTLIST rangefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	surroundtext CDATA #IMPLIED	
	startname CDATA #IMPLIED	
	endname CDATA #IMPLIED
	ruleequal (T | F) #IMPLIED
	rulemessage CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
>
<!ELEMENT textfield EMPTY>
<!ATTLIST textfield
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	default CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
>
<!ELEMENT buttons (button+)>
<!ELEMENT button (listener*)>
<!ATTLIST button
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	type (SUBMIT | RESET | BUTTON | CLEAR) #REQUIRED
	img CDATA #IMPLIED
	swpimg CDATA #IMPLIED
	alt CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT listener EMPTY>
<!ATTLIST listener
	event (onFocus | onBlur | onChange | onKeyUp | onKeyDown | onMouseUp | onMouseDown | onClick | onDblClick) #REQUIRED
	type (JS | JSRS) #REQUIRED
	action CDATA #IMPLIED
	remote CDATA #IMPLIED
	callback CDATA #IMPLIED
	params CDATA #IMPLIED
	file CDATA #IMPLIED
	debug (T | F) #IMPLIED
	autodispatchif CDATA #IMPLIED
>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
	type (REGEX | EQ | NEQ | GT | LT | GOET | LOET | REQIF | REQIFEQ | REQIFNEQ | REQIFGT | REQIFLT | REQIFGOET | REQIFLOET) #REQUIRED
	field CDATA #IMPLIED
	value CDATA #IMPLIED
	message CDATA #IMPLIED
	comparetype (STRING | INTEGER | FLOAT | DATE) #IMPLIED
>
<!ELEMENT search EMPTY>
<!ATTLIST search
	alias CDATA #IMPLIED
	datatype (STRING | INTEGER | FLOAT | DATE | DATETIME) #IMPLIED
	operator (EQ | NEQ | GT | LT | GOET | LOET | STARTING | ENDING | CONTAINING | IN | NOTIN | BETWEEN) #IMPLIED
	sqlfunc CDATA #IMPLIED
	fieldfunc CDATA #IMPLIED
	valuefunc CDATA #IMPLIED
>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	id CDATA #REQUIRED
	label CDATA #REQUIRED
	expression CDATA #REQUIRED
	mask CDATA #IMPLIED
>
<!ELEMENT datasource (keyfield, displayfield?, lookuptable, clause?, groupby?, orderby?, limit?, groupfield?, groupdisplay?, procedure?)>
<!ATTLIST datasource
	connection CDATA #IMPLIED
>
<!ELEMENT keyfield (#PCDATA)>
<!ELEMENT displayfield (#PCDATA)>
<!ELEMENT lookuptable (#PCDATA)>
<!ELEMENT clause (#PCDATA)>
<!ELEMENT groupby (#PCDATA)>
<!ELEMENT orderby (#PCDATA)>
<!ELEMENT limit (#PCDATA)>
<!ELEMENT groupfield (#PCDATA)>
<!ELEMENT groupdisplay (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ATTLIST procedure
	cursorname CDATA #IMPLIED
>
<!ELEMENT option (listener*)>
<!ATTLIST option
	value CDATA #REQUIRED
	caption CDATA #IMPLIED
	alt CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT fieldset (editfield*, passwdfield*, memofield*, checkfield*, lookupfield*, radiofield*, dbradiofield*, checkgroup*, combofield*)>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectwine.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>
   
    <section name="" id="selectWine" required_flag="T" required_color="#FF0000" required_char="*">
        <hiddenfield name="estate_id"/>
        <hiddenfield name="is_next"/>
        <hiddenfield name="pageid"/>
        <hiddenfield name="search_key"/>
        <hiddenfield name="search_id"/>

        <hiddenfield name="indexs"/>
        <hiddenfield name="wine_ids"/>

        <hiddenfield name="unwine_ids" />
        <hiddenfield name="customer_id"/>
        <hiddenfield name="isWine" value="0"/>
        <hiddenfield name="is_international" value="0"/>

        <combofield name="wine_id" tabindex="1"  label="Select wine" nofirst="T" multiple="T" size="25" width="480" >
            <option value="0" caption="" />
            <listener type="JS" event="ondblclick" action="openNextPage(0)"/>
        </combofield>


		<buttons>
        	<button name="btnAlctAll" type="BUTTON" value="Update all" tabindex="2">
    		      <listener type="JS" event="onClick" action="findallocateWine(1)"/>
    		</button>
        	<button name="btnAllocate" type="BUTTON" value="Next" tabindex="2">
    		      <listener type="JS" event="onClick" action="openNextPage(0)"/>
    		</button>
    		
           
           
           <button name="btnClose" type="BUTTON" value="Cancel" tabindex="3"/>
		</buttons>
      
	</section>	

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/selectSalesCommissionType.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="Beer" id="addbeer" required_flag="T" required_color="#FF0000" required_char="*">
	
        <hiddenfield name="pageid" value="0"/>
        <hiddenfield name="org_lkup_sales_commission_type_id" value="0"/>



        <lookupfield name="province_id" label="Province" tabindex="4" default="1" nofirst="T" multiple="F" size="1" width="250" >
            <datasource>
                <keyfield>province_id</keyfield>
                        <displayfield>province_name</displayfield>
                        <clause>province_id!=0 and province_id&lt;3</clause>
                        <orderby>province_id</orderby>
                <lookuptable>lkup_provinces</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="setUsersByProvince_id()"/>

        </lookupfield>
		
        <lookupfield name="user_id" label="Sales consultant" nofirst="T" multiple="F" size="1" width="250" disabled="F" tabindex="4">
			<datasource>
				<keyfield>user_id</keyfield>
                    <displayfield>concat(first_name,' ',last_name)</displayfield>
                    <orderby>first_name</orderby>
                    <clause>deleted=0 and lkup_user_type_id = 1</clause>
				<lookuptable>users</lookuptable>
			</datasource>
			
			<listener type="JS" event="onchange" action="setCommissionTypeByUser()"/>
		</lookupfield>
		
		<lookupfield name="lkup_sales_commission_type_id" label="Commission type" nofirst="T" multiple="F" size="1" width="250" disabled="F" tabindex="4">
			<datasource>
				<keyfield>lkup_sales_commission_type_id</keyfield>
                	<displayfield>Caption</displayfield>
                    <orderby>lkup_sales_commission_type_id</orderby>                                
				<lookuptable>lkup_sales_commission_types</lookuptable>
			</datasource>
		</lookupfield>



        <buttons>   
	        <button name="btnNext" type="BUTTON"  value="Next"  >
		        <listener type="JS" event="onClick" action="openPage(1)"/>
		    </button>
    		
		    
    	    <button name="btnCancel" type="BUTTON"  value="Close" />
        </buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/searchPeriod.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="searchf60" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="search_id" value="0"/>
                <hiddenfield name="contact_key" value="1"/>


        <combofield name="fiscal_year" default="1" nofirst="T">
        <option value="1" caption="Apr 01,2006 - Mar 31,2007" />
          <!--listener event="onChange" type="JS" action="changeFisalYear(this.value);" /-->
      </combofield>


        <combofield name="period" default="1" nofirst="T">
            <option value="1" caption="Period 1" select/>
            <option value="2" caption="Period 2" />
          <!--listener event="onChange" type="JS" action="changeFisalYear(this.value);" /-->
      </combofield>
      
	
		<buttons>
    		<button name="btnView" type="BUTTON" value="View sales reports" tabindex="2">
    		      <!--listener type="JS" event="onClick" action="gosearch()"/-->
    		</button>
			<button name="btnClose" type="BUTTON" value="Cancel" tabindex="3"/>
		</buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/generateAnaData.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="selectperiod" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="pageid" value="42"/>
                <hiddenfield name="is_recreate" value="0"/>
                <hiddenfield name="contact_key" value="1"/>
                <hiddenfield name="province_id" value="~current_province_id~"/>


      
       <lookupfield name="sale_year"  lable="Year" tabindex="2"  nofirst="T" multiple="F" size="1" width="100" >
            <datasource>
                <keyfield>distinct year(sale_date)</keyfield>
                        <displayfield>year(sale_date) sale_year </displayfield>
                        <orderby>year(sale_date)</orderby>
                        <clause>province_id=~current_province_id~ and year(sale_date)>2013</clause>
                <lookuptable>ssds_sales</lookuptable>
            </datasource>
            
            <listener type="JS" event="onChange" action="getMonthBySaleYear(this.value)"/>

        </lookupfield>
      
      


        <combofield lable="Month" name="sale_month" nofirst="T" width="100"  >
 			<listener type="JS" event="onChange" action="checkASAvaData();"/>
        </combofield>
	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/CSOrderEdit.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="Edit CSOrder" id="csOrderEdit" required_flag="T" required_color="#FF0000" required_char="*">
         <hiddenfield name="pageid" value="100"/>

	
        <hiddenfield name="order_id"/>
     
        <hiddenfield name="GST_factor"/>
        <hiddenfield name="PST_factor"/>
        
        <hiddenfield name="is_other_delivery" value="1"/>
        
        
        <hiddenfield name="isPST" value="1"/>
        <hiddenfield name="discType" value="0"/>
  
         <hiddenfield name="estate_id"/>
       
         <hiddenfield name="customer_id"/>
         
         <hiddenfield name="province_id" value="1"/>
       
         
      
      
         <editfield name="pst_no" value="" length="12">
             <listener type="JS" event="onfocus" action="this.select();"/>
              <listener type="JS" event="onchange" action="formDirty=true;"/>
              <listener type="JS" event="onkeyup" action="isEmptyPSTNo(this.value);"/>        
              <listener type="JS" event="onblur" action="showPSTNOMSG(this.value);"/>
        </editfield>
        <textfield name="customer_name" label="Name: "/>
        
        <textfield name="customer_address" label="Address: "/>
        <textfield name="product_name" label="Product: " />
        <textfield name="invoice_number" label="Invoice#: " />
        <textfield name="licensee_number" label="Licensee/Agency/LRS/Store number: " />

        <textfield name="created_by_user_name" label="Created by: "/>
        <textfield name="when_entered" label="Created on: " />
        <textfield name="when_modified" label="Updated on: " />
        <textfield name="estate_number" label="Store: " />
        <textfield name="license_name" label="Customer type: " />
        <editfield name="delivery_date" label="Delivery date: " mask="DATE" default="go_TODAY" size="20" length="10" required="T" >
            <listener type="JS" event="onchange" action="formDirty=true;"/>
        </editfield>     
        
        <editfield name="disc_2"  length="2" size="5">
             <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
            <listener type="JS" event="onchange" action="formDirty=true;"/>
            <listener type="JS" event="onfocus" action="this.value=filterNum(this.value);this.select();"/>
             <listener type="JS" event="onblur" action="orderCalculation();"/>
        </editfield>
        
         <editfield name="disc_1" length="5" value="0" size="5">
            <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
             <listener type="JS" event="onchange" action="formDirty=true;"/>
            <listener type="JS" event="onfocus" action="this.value=filterNum(this.value);this.select();"/>
             <listener type="JS" event="onblur" action="orderCalculation();"/>
        </editfield>
        
         
        
        <lookupfield name="lkup_order_status_id" label="Order status: "   default="2" nofirst="T" multiple="F" size="1" width="100" >
            <datasource>
                <keyfield>lkup_order_status_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>caption</orderby>
                <lookuptable>lkup_order_statuses</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="formDirty=true;"/>
        </lookupfield>
        
    
            <lookupfield name="lkup_payment_type_id" label="Payment method: "  default="6" nofirst="T" multiple="F" size="1" width="100" >
            <datasource>
                <keyfield>lkup_payment_type_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>caption</orderby>
                        <clause>lkup_payment_type_id!=5 and lkup_payment_type_id!=3 and lkup_payment_type_id!=4</clause>
                <lookuptable>lkup_payment_types</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="formDirty=true;"/>
        </lookupfield>
        
        <lookupfield name="lkup_payment_status_id" label="Payment status: "  default="2"   nofirst="T" multiple="F" size="1" width="100" >
            <datasource>
                <keyfield>lkup_payment_status_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>caption</orderby>
                <lookuptable>lkup_order_payment_status</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="formDirty=true;"/>
        </lookupfield>
        <editfield name="adjustment_1" label="Adjustment 1" length="12" align="RIGHT" default="$0.00">
                <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
                <listener type="JS" event="onblur" action="this.value=formatCurrency(this.value);orderCalculation();"/>
                <listener type="JS" event="onfocus" action="this.value=filterNum(this.value);this.select();"/>
               <listener type="JS" event="onchange" action="formDirty=true;"/>
        </editfield>
        <!-- editfield name="adjustment_2" label="Adjustment 2" length="12" align="RIGHT" default="$0.00">
                <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
                <listener type="JS" event="onblur" action="this.value=formatCurrency(this.value);orderCalculation();"/>
                <listener type="JS" event="onfocus" action="this.value=filterNum(this.value);this.select();"/>
                <listener type="JS" event="onchange" action="formDirty=true;"/>
        </editfield -->
     
        <editfield name="other_info" length="20" value="" size="18">
         </editfield>
                

        <buttons>
                <button name="btnOK" type="BUTTON"  value="OK  " />
                <button name="btnCancel" type="BUTTON" value="Cancel" />
        </buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/addwineCa.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="Wine" id="addwineca" required_flag="T" required_color="#FF0000" required_char="*">
	
        <hiddenfield name="pageid" value="25"/>

        <hiddenfield name="editMode"/>
        <hiddenfield name="wineid"/>
        <hiddenfield name="wine_delivery_date_id"/>
        <hiddenfield name="estate_id"/>
        <hiddenfield name="delivery_total" value="0"/>
        <hiddenfield name="total_bottles" value="0"/>
        <hiddenfield name="price_per_unit" />
        <hiddenfield name="price_winery" />
        <hiddenfield name="is_international" value="0" />        

        <editfield name="wine_name" label="Wine name"  tabindex="1" size="47" length="225" required="T"/>

        <lookupfield name="lkup_bottle_size_id" label="Size"  tabindex="2" default="1" nofirst="T" multiple="F" size="1" width="78" >
            <datasource>
                <keyfield>lkup_bottle_size_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>lkup_bottle_size_id</orderby>
                <lookuptable>lkup_bottle_sizes</lookuptable>
            </datasource>
        </lookupfield>

        <lookupfield name="lkup_wine_color_type_id" label="Type"  tabindex="2" default="1" nofirst="T" multiple="F" size="1" width="82" >
            <datasource>
                <keyfield>lkup_wine_color_type_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>lkup_wine_color_type_id</orderby>
                <lookuptable>lkup_wine_color_types</lookuptable>
            </datasource>
        </lookupfield>
        <editfield name="cspc_code" label="CSPC code" tabindex="3" size="22" length="25" required="T"/>
        <editfield name="vintage" label="Vintage"     tabindex="4" size="22" length="4" minlength="4" required="T" mask="INTEGER"/>

        <editfield name="price" label="Display price" tabindex="5" size="12" length="12" required="T" >
            <listener type="JS" event="onblur" action="setPrice(this,0)"/>
             <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
        </editfield>

		 <editfield name="wholesale" label="CSWS price" tabindex="6" size="14" length="12"  required="T">
            <listener type="JS" event="onblur" action="setPrice(this,1)"/>
            <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
        </editfield>

        <editfield name="delivery_date" label="Delivery date" mask="DATE"  default="go_TODAY" size="12" length="10" required="T" tabindex="7" />

        <editfield name="total_cases" label="Total cases"   tabindex="7" size="25" length="8" required="T" mask="INTEGER">
            <listener type="JS" event="onblur" action="getBottles(this.value)"/>
        </editfield>

        <editfield name="bottles_per_case" label="Bottles / case" tabindex="8" size="22" length="3" required="T"  mask="INTEGER">
            <listener type="JS" event="onblur" action="getBottles(this.value)"/>
        </editfield>

        <editfield name="show_total_bottles" label="Total bottles" tabindex="9" size="22" length="12" readonly="T" default=""/>

        <buttons>
      	  <button name="btnAdd" type="BUTTON"  value="OK  " />
        	  <button name="btnCancel" type="BUTTON" value="Cancel" />
        </buttons>

	</section>

</form>
