=== HelenCSWS/CS-Online/php2go/docs/dtd/php2go_forms.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- DTD que especifica a forma de construção dos arquivos XML de formulários do PHP2Go -->
<!-- $Header: /www/cvsroot/php2go/docs/dtd/php2go_forms.dtd,v 1.22 2005/09/01 13:55:42 mpont Exp $ -->
<!-- $Revision: 1.22 $ -->
<!-- $Date: 2005/09/01 13:55:42 $ -->
<!ELEMENT form (section+, condsection*)>
<!ATTLIST form
	validatefunc CDATA #IMPLIED
>
<!ELEMENT section (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, datagrid*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST section
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	condition (T | F) #IMPLIED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT condsection (condsection*, editfield*, editselectionfield*, rangefield*, passwdfield*, memofield*, editorfield?, checkfield*, filefield*, lookupfield*, lookupchoicefield*, lookupselectionfield*, radiofield*, dbradiofield*, checkgroup*, combofield*, hiddenfield*, textfield*, buttons*, button*)>
<!ATTLIST condsection
	id CDATA #REQUIRED
	evalfunction CDATA #IMPLIED
	required_flag (T | F) #IMPLIED
	required_color CDATA #IMPLIED
	required_text CDATA #IMPLIED
>
<!ELEMENT captchafield (listener*, rule*)>
<!ATTLIST captchafield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	noiselevel CDATA #IMPLIED
	fontsize CDATA #IMPLIED
	fontshadow CDATA #IMPLIED	
	fontangle CDATA #IMPLIED
	imagepath CDATA #IMPLIED
	imagetype CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED	
>
<!ELEMENT checkfield (listener*, rule*, search?)>
<!ATTLIST checkfield
	name CDATA #REQUIRED
	label CDATA #IMPLIED
	default CDATA #IMPLIED
	caption CDATA #REQUIRED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT checkgroup (option+, listener*, rule*, search?)>
<!ATTLIST checkgroup
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT combofield (option+, listener*, rule*, search?)>
<!ATTLIST combofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple CDATA #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT dbradiofield (datasource, listener*, rule*, search?)>
<!ATTLIST dbradiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED	
>
<!ELEMENT editfield (listener*, rule*, search?)>
<!ATTLIST editfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	mask (INTEGER | FLOAT | LOGIN | DATE | TIME | CPFCNPJ | CURRENCY | URL | EMAIL | ZIPnn) #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	calculator (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	capitalize (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
>
<!ELEMENT editorfield EMPTY>
<!ATTLIST editorfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT editsearchfield (datafilter+, datasource, lookupfield, listener*)>
<!ATTLIST editsearchfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	btnvalue CDATA #IMPLIED
	btnimg CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	autocomplete (T | F) #IMPLIED
	autotrim (T | F) #IMPLIED
	required (T | F) #IMPLIED	
	disabled (T | F) #IMPLIED	
	debug (T | F) #IMPLIED
>
<!ELEMENT editselectionfield (editfield, lookupfield)>
<!ATTLIST editselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	tablewidth CDATA #IMPLIED
>
<!ELEMENT filefield (listener*, rule*)>
<!ATTLIST filefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED	
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	maxfilesize CDATA #IMPLIED
	allowedtypes CDATA #IMPLIED
	savefunction CDATA #IMPLIED
	savepath CDATA #IMPLIED
	savename CDATA #IMPLIED
	savemode CDATA #IMPLIED
	overwrite (T | F) #IMPLIED
	uploadonvalidate (T | F) #IMPLIED
>
<!ELEMENT datagrid (datasource, fieldset)>
<!ATTLIST datagrid
	name CDATA #REQUIRED
	label CDATA #REQUIRED	
	headerstyle CDATA #IMPLIED
	cellstyle CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	cellsizes CDATA #IMPLIED
	help CDATA #IMPLIED	
	disabled (T | F) #IMPLIED	
>
<!ELEMENT hiddenfield (search?)>
<!ATTLIST hiddenfield
	name CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
>
<!ELEMENT lookupchoicefield (datasource, listener*, rule*, search?)>
<!ATTLIST lookupchoicefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT lookupfield (datasource?, listener*, rule*, search?)>
<!ATTLIST lookupfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	first CDATA #IMPLIED
	nofirst CDATA #IMPLIED
	multiple (T | F) #IMPLIED
	size CDATA #IMPLIED
	width CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	size CDATA #IMPLIED
>
<!ELEMENT lookupselectionfield (lookupfield+)>
<!ATTLIST lookupselectionfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	insfield CDATA #IMPLIED
	remfield CDATA #IMPLIED
	tablewidth CDATA #IMPLIED
	addimg CDATA #IMPLIED
	addallimg CDATA #IMPLIED
	remimg CDATA #IMPLIED
	remallimg CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
>
<!ELEMENT memofield (listener*, rule*, search?)>
<!ATTLIST memofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED	
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
	charcount (T | F) #IMPLIED
>
<!ELEMENT passwdfield (listener*, rule*, search?)>
<!ATTLIST passwdfield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #IMPLIED
	default CDATA #IMPLIED
	size CDATA #IMPLIED
	length CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	minlength CDATA #IMPLIED
	align (LEFT | CENTER | RIGHT) #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	autocomplete (T | F) #IMPLIED
	required (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	upper (T | F) #IMPLIED
	lower (T | F) #IMPLIED
>
<!ELEMENT radiofield (option+, listener*, rule*, search?)>
<!ATTLIST radiofield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	default CDATA #IMPLIED
	cols CDATA #IMPLIED
	tablewidth CDATA #IMPLIED	
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT rangefield (edifield*, search?)>
<!ATTLIST rangefield
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	surroundtext CDATA #IMPLIED	
	startname CDATA #IMPLIED	
	endname CDATA #IMPLIED
	ruleequal (T | F) #IMPLIED
	rulemessage CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
	required (T | F) #IMPLIED
	disabled (T | F) #IMPLIED
	readonly (T | F) #IMPLIED
>
<!ELEMENT textfield EMPTY>
<!ATTLIST textfield
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	default CDATA #IMPLIED
	style CDATA #IMPLIED
	help CDATA #IMPLIED		
>
<!ELEMENT buttons (button+)>
<!ELEMENT button (listener*)>
<!ATTLIST button
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	type (SUBMIT | RESET | BUTTON | CLEAR) #REQUIRED
	img CDATA #IMPLIED
	swpimg CDATA #IMPLIED
	alt CDATA #IMPLIED
	style CDATA #IMPLIED
	tabindex CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT listener EMPTY>
<!ATTLIST listener
	event (onFocus | onBlur | onChange | onKeyUp | onKeyDown | onMouseUp | onMouseDown | onClick | onDblClick) #REQUIRED
	type (JS | JSRS) #REQUIRED
	action CDATA #IMPLIED
	remote CDATA #IMPLIED
	callback CDATA #IMPLIED
	params CDATA #IMPLIED
	file CDATA #IMPLIED
	debug (T | F) #IMPLIED
	autodispatchif CDATA #IMPLIED
>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
	type (REGEX | EQ | NEQ | GT | LT | GOET | LOET | REQIF | REQIFEQ | REQIFNEQ | REQIFGT | REQIFLT | REQIFGOET | REQIFLOET) #REQUIRED
	field CDATA #IMPLIED
	value CDATA #IMPLIED
	message CDATA #IMPLIED
	comparetype (STRING | INTEGER | FLOAT | DATE) #IMPLIED
>
<!ELEMENT search EMPTY>
<!ATTLIST search
	alias CDATA #IMPLIED
	datatype (STRING | INTEGER | FLOAT | DATE | DATETIME) #IMPLIED
	operator (EQ | NEQ | GT | LT | GOET | LOET | STARTING | ENDING | CONTAINING | IN | NOTIN | BETWEEN) #IMPLIED
	sqlfunc CDATA #IMPLIED
	fieldfunc CDATA #IMPLIED
	valuefunc CDATA #IMPLIED
>
<!ELEMENT datafilter EMPTY>
<!ATTLIST datafilter
	id CDATA #REQUIRED
	label CDATA #REQUIRED
	expression CDATA #REQUIRED
	mask CDATA #IMPLIED
>
<!ELEMENT datasource (keyfield, displayfield?, lookuptable, clause?, groupby?, orderby?, limit?, groupfield?, groupdisplay?, procedure?)>
<!ATTLIST datasource
	connection CDATA #IMPLIED
>
<!ELEMENT keyfield (#PCDATA)>
<!ELEMENT displayfield (#PCDATA)>
<!ELEMENT lookuptable (#PCDATA)>
<!ELEMENT clause (#PCDATA)>
<!ELEMENT groupby (#PCDATA)>
<!ELEMENT orderby (#PCDATA)>
<!ELEMENT limit (#PCDATA)>
<!ELEMENT groupfield (#PCDATA)>
<!ELEMENT groupdisplay (#PCDATA)>
<!ELEMENT procedure (#PCDATA)>
<!ATTLIST procedure
	cursorname CDATA #IMPLIED
>
<!ELEMENT option (listener*)>
<!ATTLIST option
	value CDATA #REQUIRED
	caption CDATA #IMPLIED
	alt CDATA #IMPLIED
	disabled (T | F) #IMPLIED
>
<!ELEMENT fieldset (editfield*, passwdfield*, memofield*, checkfield*, lookupfield*, radiofield*, dbradiofield*, checkgroup*, combofield*)>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/searchInvoice.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="supplierSales" required_flag="T" required_color="#FF0000" required_char="*">
        <hiddenfield name="current_estate_id" value="0"/>
        <hiddenfield name="user_id" id="user_id" value="0"/>
	 <hiddenfield name="estate" value="0"/>
	
	<combofield name="estate_id" label="Estate" nofirst="F" multiple="F" size="1" width="130" disabled="F" tabindex="4">       
          <option value="-1" caption="All" />
          <option value="97" caption="LaStella" />
          <option value="96" caption="Le Vieux Pin" />
    </combofield>

    <combofield name="search_type" label="Search for" width="125" tabindex="13" disabled="F" nofirst="T" default="-1" >
      <option value="1" caption="Customer"/>
      <option value="2" caption="Invoice"/>
      <option value="3" caption="License number"/>
      <option value="4" caption="Street name"/>
      <listener event="onChange" type="JS" action="changeSearchFeild();" />
	</combofield>
	

      
    <editField class="Lable" name="search_field" tabindex="1" value="" size="20">
    		<listener type="JS" event="onKeyPress" action="handleEnter(this, event, getinvoices)"/>
    </editField>
    
    
 			
<!-- 2 section end here-->


		<!--buttons>
    		<button name="btnRefresh" type="BUTTON" value="Generate" disabled="T">
    		      <listener type="JS" event="onClick" action="refreshSpSalesList()"/>
    		</button>
    	
		</buttons-->



	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/invoiceSearch.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="supplierSales" required_flag="T" required_color="#FF0000" required_char="*">
        <editField name="current_estate_id" value="0"/>
        <editField name="user_id" id="user_id" value="0"/>
	
	<combofield name="estate_id" label="Estate" nofirst="F" multiple="F" size="1" width="130" disabled="F" tabindex="4">       
          <option value="-1" caption="All" />
          <option value="97" caption="LaStella" />
          <option value="96" caption="Le Vieux Pin" />
    </combofield>

    <combofield name="search_type" label="Search for" width="95" tabindex="13" disabled="F" nofirst="T" default="-1" >
      <option value="1" caption="Customer"/>
      <option value="2" caption="Invoice"/>
      <option value="3" caption="License number"/>
      <option value="4" caption="Street name"/>
      <listener event="onChange" type="JS" action="changeSearchFeild();" />
	</combofield>
      
    <editField class="Lable" name="search_field" tabindex="1" value="   " readonly="T" size="20"/>
 			
<!-- 2 section end here-->


		<!--buttons>
    		<button name="btnRefresh" type="BUTTON" value="Generate" disabled="T">
    		      <listener type="JS" event="onClick" action="refreshSpSalesList()"/>
    		</button>
    	
		</buttons-->



	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/searchf60.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >
    
	<section name="" id="searchf60" required_flag="T" required_color="#FF0000" required_char="*">
                <hiddenfield name="search_id" value="0"/>
                <hiddenfield name="search_id_w" value="0"/>
                <hiddenfield name="contact_key" value="1"/>
                <hiddenfield name="isWine" value="0"/>
                <hiddenfield name="isQtr" value="0"/>
                <hiddenfield name="isStart" value="0"/>                
	
				<hiddenfield name="province_id" value="1"/>
				
				<editfield name="search_field" label="Search for" tabindex="1" size="40" length="225" value="">
				    <listener type="JS" event="onKeyPress" action="handleEnter(this, event, gosearch)"/>
				</editfield>
				
				<editfield name="street_name"   size="28" length="225" Disabled="T"/>
		
		<lookupfield name="lkup_store_type_id" default="1" label="Store type" nofirst="T" multiple="F" size="1" width="150" disabled="F" tabindex="4">
			<datasource>
				<keyfield>lkup_store_type_id</keyfield>
                                <displayfield>license_name</displayfield>
                                <orderby>license_name</orderby>
                                <clause>province_id =~current_province_id~</clause>
				<lookuptable>lkup_store_types</lookuptable>
			</datasource>
		</lookupfield>

		<lookupfield name="user_id" label="Assigned to" nofirst="T" multiple="F" size="1" width="150" disabled="T" tabindex="4">
			<datasource>
				<keyfield>user_id</keyfield>
                                <displayfield>concat(first_name,' ',last_name)</displayfield>
                                <orderby>first_name</orderby>                               
                                <clause>deleted=0 and lkup_user_type_id =1 and (province_id=-1 or province_id = ~current_user_province_id~) or user_id =0</clause>
				<lookuptable>users</lookuptable>
			</datasource>
		</lookupfield>

		<lookupfield name="estate_id" nofirst="T" multiple="F" size="1" width="200" disabled="T" tabindex="4" label="Estates" default="2">
			<datasource>
				<keyfield>estate_id</keyfield>
                                <displayfield>estate_name</displayfield>
                                <orderby>billing_address_country, estate_name</orderby>
                                <clause> (~BC_ESTATES~ billing_address_country = 'CSWS Products') and deleted =0</clause>
                                <!-- clause> (billing_address_country = 'Canada' or billing_address_country = 'CSWS Products') and deleted =0</clause -->
				<lookuptable>estates</lookuptable>
			</datasource>
		</lookupfield>
		
		
     <combofield name="contact" default="2" nofirst="T">
        <option value="1" caption="First" />
          <option value="2" caption="Last" />
          <listener event="onChange" type="JS" action="changeName(this.value);" />
      </combofield>
      
      
      <combofield name="product_id" label="Products" default="1" nofirst="T" width="120">
        <option value="1" caption="Wine" />
          <option value="2" caption="Beer" />
          <option value="3" caption="Sake" />
          <option value="4" caption="Spirits" />
          <listener event="onChange" type="JS" action="setProductId(this.value);" />
      </combofield>
      
      

<!-- 2 section-->
	<editfield name="search_field_w" label="Search for" tabindex="1" size="28" length="225" >
        <listener type="JS" event="onKeyPress" action="handleEnter(this, event, searchWines)"/>
    </editfield>
	
	<editfield name="city"   size="12" length="225" Disabled="F" tabindex="2" value="">
		<listener type="JS" event="onKeyPress" action="handleEnter(this, event, searchWines)"/>
	</editfield>
	
	<combofield name="sales_month" label="Month" width="94" tabindex="13" nofirst="T" disabled="T">
          <option value="1" caption="January" />
          <option value="2" caption="February" />
          <option value="3" caption="March" />
          <option value="4" caption="April" />
          <option value="5" caption="May" />
          <option value="6" caption="June" />
          <option value="7" caption="July" />
          <option value="8" caption="August" />
          <option value="9" caption="September" />
          <option value="10" caption="October" />
          <option value="11" caption="November" />
          <option value="12" caption="December" />
	</combofield>
    
      
	<combofield name="sales_year" label="Year" width="68" tabindex="13" nofirst="T" default="2019">
	
		<option value="2014" caption="2014" />
		<option value="2015" caption="2015" />
		<option value="2016" caption="2016" />
		<option value="2017" caption="2017" />
		<option value="2018" caption="2018" />
        <option value="2019" caption="2019" />
		<option value="-1" caption="All" />
	</combofield>
      
	<combofield name="sales_qut" label="" width="78" tabindex="13" disabled="F" nofirst="T" default="-1">
	  <option value="1" caption="First" />
	  <option value="2" caption="Second" />
	  <option value="3" caption="Third" />
	  <option value="4" caption="Fourth" />
	  <option value="-1" caption="YTD" />
	  <listener type="JS" event="onChange" action="setQuarterDesc()"/>
	</combofield>
      
    <editField class="Lable" name="quarter_desc" tabindex="1" value="   " readonly="T" size="20"/>
      
      
	<combofield name="lkup_store_type_id_w" label="Store type" nofirst="F" multiple="F" size="1" width="140" disabled="F" tabindex="4" default ="-1">      
		
	</combofield>
     <!--lookupfield name="lkup_store_type_id_w" label="Store type" nofirst="F" multiple="F" size="1" width="140" disabled="F" tabindex="4">
			<datasource>
				<keyfield>lkup_store_type_id</keyfield>
                                <displayfield>license_name</displayfield>
                                <orderby>license_name</orderby>
                                <clause>province_id =~current_province_id~</clause>
				<lookuptable>lkup_store_types</lookuptable>
			</datasource>
		</lookupfield-->
		

		<lookupfield name="user_id_w" label="Assigned to" nofirst="F" multiple="F" size="1" width="140" disabled="F" tabindex="4">
			<datasource>
				<keyfield>user_id</keyfield>
                                <displayfield>concat(first_name,' ',last_name)</displayfield>
                                <orderby>first_name</orderby>
                                <clause>deleted=0 and lkup_user_type_id =1 and (province_id=-1 or province_id = ~current_user_province_id~)</clause>
				<lookuptable>users</lookuptable>
			</datasource>
		</lookupfield>
		
		<combofield name="is_purchased" label="" width="108" tabindex="18" disabled="F" nofirst="T">
          <option value="1" caption="Purchased" />
          <option value="2" caption="Not purchased" />        
      </combofield>
      
      <combofield name="cm_number" label="" width="48" tabindex="18" disabled="F" nofirst="T">
          <option value="5" caption="5" />
          <option value="10" caption="10" />
          <option value="15" caption="15" />
          <option value="20" caption="20" />
          <option value="25" caption="25" />
          <option value="50" caption="50" />
          <option value="100" caption="100" />

      </combofield>
      
      <combofield name="wine_number" label="" width="48" tabindex="18" disabled="F" nofirst="T">
          <option value="5" caption="5" />
          <option value="10" caption="10" />
          <option value="15" caption="15" />
          <option value="20" caption="20" />
          <option value="25" caption="25" />
          <option value="50" caption="50" />
          <option value="100" caption="100" />
          <option value="-1" caption="All" />

      </combofield>
      
      <combofield name="lkup_wine_color_type_id" label="Type"  tabindex="4" default="-1" nofirst="F" multiple="F" size="1" width="90" >
          
           
        </combofield>
        
        <combofield name="sku_name" label="" width="98" tabindex="18" disabled="F" nofirst="T">
          <option value="1" caption="SKU/CSPC" />
          <option value="2" caption="Product name" />        
      </combofield>
			
<!-- 2 section end here-->


		<buttons>
    		<button name="btnSearch" type="BUTTON" value="Search" tabindex="2">
    		      <listener type="JS" event="onClick" action="gosearch()"/>
    		</button>
    		<button name="btnSearch_w" type="BUTTON" value="Search" tabindex="2">
    		      <listener type="JS" event="onClick" action="searchWines()"/>
    		</button>
			<button name="btnClose" type="BUTTON" value="Cancel" tabindex="3"/>
		</buttons>

	</section>

</form>

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/summaryreport.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Form60 : template used in AddUser.php -->
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form >


	<section name="My Section" id="summaryreport" required_flag="T" required_color="#FF0000" required_char="*">
		
			<hiddenfield name="sale_month" value="0"/>
			<hiddenfield name="sale_year" value="0"/>
			<hiddenfield name="bonus_type" value="-1"/>
			<hiddenfield name="is_recreate" value="0"/>
		
			<hiddenfield name="fiscal_year_4" value="-1"/>
			<hiddenfield name="users" value="1"/>
			<hiddenfield name="current_user_id" value="-1"/>
			<hiddenfield name="store_type" value="-1"/>
		
		   <textfield name="period_desc" tabindex="1" value="" size="100"/>
		   <textfield name="target_inter_cases" tabindex="1" value="" size="10"/>
		   <textfield name="target_ca_cases" tabindex="1" value="" size="10"/>
		     
        <combofield name="user_id"  nofirst="F" multiple="F" size="1" width="200" tabindex="17">
				<listener event="onChange" type="JS" action="changeuser();" />
		  </combofield>
		
		 <combofield name="store_types"  nofirst="F" multiple="F" size="1" width="120" tabindex="17">
			<option value="-1" caption="All store type" />
          	<option value="3" caption="Licensee" />
         	<option value="1" caption="LRS" />
         	<option value="2" caption="Agency" />
         
			<listener event="onChange" type="JS" action="changeType(this.value);" />
		 </combofield>
		
		<combofield name="store_type_all"  nofirst="F" multiple="F" size="1" width="120" tabindex="17">
			<option value="-1" caption="All store type" />
		</combofield>

		<combofield name="store_type_bcldb"  nofirst="F" multiple="F" size="1" width="120" tabindex="17">
			<option value="6" caption="BCLDB" />
		</combofield>
        <!--buttons note -->
		<buttons>
			
     		<button name="btnCancel" type="BUTTON" value="Close" tabindex="28"/>
		</buttons>


	</section>

</form>



	<!-- Form60 : template used in addestate.php -->

=== HelenCSWS/CS-Online/php2go/Form60/resources/xml/addCSProduct.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE form SYSTEM "..\..\docs\dtd\php2go_forms.dtd">
<form>

	<section name="CSProductAdd" id="CSProductAdd" required_flag="T" required_color="#FF0000" required_char="*">
	
        <hiddenfield name="pageid" value="57"/>
        <hiddenfield name="editMode" value="0"/>
        <hiddenfield name="product_id"/>
        <hiddenfield name="product_ids"/>
        <hiddenfield name="estate_id"/>
        <hiddenfield name="isAddNew" value="0"/>
        <hiddenfield name="isAdmin" value="0"/>
        <hiddenfield name="delete_id" value="0"/>
        <hiddenfield name="basicChanged" value="0"/>
        <hiddenfield name="infoChanged" value="0"/>
        
        <hiddenfield name="user_level" value="4"/>
        
        <hiddenfield name="total_units" value="0"/>
        
        <hiddenfield name="current_province_id" value="1"/>
        
        
         <hiddenfield name="isAddAnother" value="0"/>
        


           <!-- 0: unchecked, 1: checked but need to insert new, 2: checked for update  -->
        <lookupfield name="province_id" label="Province"  default="1" nofirst="T" multiple="F" size="1" width="130" >
            <datasource>
                <keyfield>province_id</keyfield>
                        <displayfield>province_name</displayfield>
                        <orderby>province_name</orderby>       
                        <clause>province_id!=0</clause>                
                <lookuptable>lkup_provinces</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="changeProductProvince(this.value);"/>
        </lookupfield>
        
		<editfield name="product_name" label="Product name"   size="30" length="225">
            <listener type="JS" event="onchange" action="setFormChange(0);"/>
        </editfield>
        
        <editfield name="product_number" label="Model#"  size="13" length="10" >
            <listener type="JS" event="onchange" action="setFormChange(0);"/>
        </editfield>
        
		<editfield name="bottles_per_case" label="Units/cs"  size="13" length="3"  mask="INTEGER" value="1">
            <listener type="JS" event="onchange" action="setFormChange(0);"/>
        </editfield>


        <lookupfield name="lkup_product_type_id" label="Type"  default="1" nofirst="T" multiple="F" size="1" width="120" >
            <datasource>
                <keyfield>lkup_product_type_id</keyfield>
                        <displayfield>caption</displayfield>
                        <orderby>display_name</orderby>
                        <clause>~productTypeFilter~</clause>
                <lookuptable>lkup_product_types</lookuptable>
            </datasource>
            <listener type="JS" event="onchange" action="setFormChange(0);"/>
        </lookupfield>     
  
        <editfield name="display_price" label="Display price"  size="13" length="12"  value="0">            
             <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
             <listener type="JS" event="onchange" action="setFormChange(1);"/>
        </editfield>

         <editfield name="special_price" label="Special price"  size="13" length="12" value="0">            
             <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
             <listener type="JS" event="onchange" action="setFormChange(1);"/>
        </editfield>

         <editfield name="cost" label="Cost"    size="13" length="8" value="0">
             <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
             <listener type="JS" event="onchange" action="setFormChange(1);"/>
        </editfield>
     
	    <editfield name="commission" label="Commission/unit"  size="13" length="12" value="0">

            <listener type="JS" event="onKeyPress" action="return chkFLOAT(this, event);"/>
            <listener type="JS" event="onchange" action="setFormChange(1);"/>
        </editfield>       
     
   		<editfield name="inventory" label="" size="13"  required="T"  mask="INTEGER" value="0"/>
      
        <buttons>       
            <button name="btnAdd" type="BUTTON"  value="Save" />      
            <button name="btnAddAnother" type="BUTTON"  value="Add new" />           
            <button name="btnCancel" type="BUTTON" value="Close" />
        </buttons>

	</section>

</form>
